# Generated by Django 3.1.7 on 2021-03-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_medicines', '0002_medicine_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
