# Generated by Django 3.1.7 on 2021-03-20 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage_medicines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.IntegerField(choices=[(1, 'debit'), (2, 'credit')])),
                ('received_amount', models.IntegerField(default=0)),
                ('quantity', models.IntegerField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_medicines.medicine')),
            ],
        ),
    ]
