# Generated by Django 3.1.7 on 2021-03-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20210320_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinetransaction',
            name='quantity',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
