# Generated by Django 3.1.7 on 2021-03-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20210320_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinetransaction',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
